### ISSUE TITLE
Refactor: Talent cannot submit form for registration

### ISSUE THREAD

**Issue by Rohith-Yogi** [CSCE-606-Event360/CastNXT#1]
Feature: User/talent can register for existing events
As a user/talent
I want to register for existing events
So that my user information appears in the event I registered for.

**Comment by ksshen0000** [comment]
Roll back the code to 38f6247c5ba4c55b0ea486bf40aa7e70a5916598. 

![Image](https://github.com/CSCE-606-Event360/CastNXT/assets/71251878/35948305-4201-44e2-9657-453be7680a44)

**Comment by Rohith-Yogi** [comment]
`git log`
`git checkout 38f6247c5ba4c55b0ea486bf40aa7e70a5916598`
