### ISSUE TITLE
Generate new UML diagram

### ISSUE THREAD

**Issue by Rohith-Yogi** [CSCE-606-Event360/CastNXT#11]
Use railroady

**Comment by ksshen0000** [comment]
`sudo apt-get install graphviz`
`bundle exec railroady -o models.dot -M  `
`dot -Tpng models.dot -o models.png`

**Comment by Rohith-Yogi** [comment]
![Image](https://github.com/CSCE-606-Event360/CastNXT/assets/142866048/23ba99de-9afa-408b-abbf-10f5094fe9de)
