### ISSUE TITLE
Edit event’s information as an admin

### ISSUE THREAD

**Issue by Rohith-Yogi** [CSCE-606-Event360/CastNXT#3]
As an admin that has some events created with wrong information.
I want to modify the info of some events when I click edit button.
So that I can correct some data of the events.

**Comment by ksshen0000** [comment]
![Image](https://github.com/CSCE-606-Event360/CastNXT/assets/71251878/6e32a504-e6ba-413a-82bf-519353034da1)



![Image](https://github.com/CSCE-606-Event360/CastNXT/assets/71251878/f8c3d6c8-3862-4027-8c04-50a959e2bb53)

**Comment by ksshen0000** [comment]
if is_user_logged_in?("ADMIN")
        eventId = params[:id]
        event = get_event(eventId)
        if params[:status]== "DELETED" || params[:status] == "ACCEPTING" || params[:status] == "REVIEWING" || params[:status] == "FINALIZED"
          update_event_status(event, params[:status])
        else 
          params[:status] = event[:status]
          edit_event(event, params)
        end

**Comment by ksshen0000** [comment]
/CastNXT/web/CASTNXT/app/controllers/events_controller.rb
