### ISSUE TITLE
Sometimes Clients are not able to see the event when assigned

### ISSUE THREAD

**Issue by Rohith-Yogi** [CSCE-606-Event360/CastNXT#4]
As a client
So that I can be know which talent I am assigned to.
I want to see the updated events.

**Comment by ksshen0000** [comment]
The Fasionxt email is not valid now. So I use personal email address. Also, since Gmail doesn't support password-only login, I have to set up 2FA and generate app specific password.

![Image](https://github.com/CSCE-606-Event360/CastNXT/assets/71251878/0f85f557-38ea-41d5-893b-bbba3290f843)
